# Generated by Django 3.1.1 on 2021-01-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.IntegerField()),
                ('tem', models.IntegerField()),
                ('hum', models.IntegerField()),
                ('water', models.IntegerField()),
                ('light', models.IntegerField()),
            ],
        ),
    ]
